- name: Debug vault token
  debug:
    msg: "GitHub token is: {{ github_token | default('not defined') }}
          medaipath: {{media_path | default('not defined') }}"

- name: Run Flux bootstrap with GitHub
  shell: |
    export GITHUB_TOKEN={{ github_token }}
    flux bootstrap github \
      --owner=JigX \
      --repository=quantika-infra \
      --branch=main \
      --path=clusters/quantika \
      --personal
  environment:
    GITHUB_TOKEN: "{{ github_token }}"
    HOME: "/home/{{ ansible_user | default('ansible') }}"
  args:
    creates: /var/lib/flux-system  # voorkomt herhaling bij reruns
