apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sealed-secrets
  namespace: kube-system
spec:
  releaseName: sealed-secrets
  interval: 5m
  chart:
    spec:
      chart: sealed-secrets
      version: 2.15.3
      sourceRef:
        kind: HelmRepository
        name: sealed-secrets
        namespace: flux-system
  install:
    createNamespace: true
  values:
    fullnameOverride: sealed-secrets