---
apiVersion: v1
kind: Namespace
metadata:
  name: media
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: media-local-path-config
  namespace: kube-system
  labels:
    app: media-local-path-provisioner
data:
  config.json: |
    {
      "nodePathMap": [
        {
          "node": "DEFAULT_PATH_FOR_NON_LISTED_NODES",
          "paths": ["/mnt/media/k8s"]
        }
      ]
    }
  helperPod.yaml: |
    apiVersion: v1
    kind: Pod
    metadata:
      name: helper-pod
      namespace: media
    spec:
      restartPolicy: Never
      containers:
        - name: helper-pod
          image: "rancher/mirrored-library-busybox:1.36.1"
          command: ["sleep", "300"]
  setup: |
    #!/bin/sh
    set -eu
    mkdir -m 0777 -p "${VOL_DIR}"
    chmod 700 "${VOL_DIR}/.."
  teardown: |
    #!/bin/sh
    set -eu
    rm -rf "${VOL_DIR}"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: media-local-path-provisioner
  namespace: media
  labels:
    app: media-local-path-provisioner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: media-local-path-provisioner
  template:
    metadata:
      labels:
        app: media-local-path-provisioner
    spec:
      serviceAccountName: local-path-provisioner-service-account
      containers:
        - name: provisioner
          image: rancher/local-path-provisioner:v0.0.31
          command:
            - local-path-provisioner
            - start
            - --config
            - /etc/config/config.json
            - --helper-pod-file
            - /etc/config/helperPod.yaml
            - --configmap-name
            - media-local-path-config
            - --service-account-name
            - local-path-provisioner-service-account
            - --namespace
            - media
          volumeMounts:
            - name: config-volume
              mountPath: /etc/config/
      volumes:
        - name: config-volume
          configMap:
            name: media-local-path-config
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: media-local-path
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: rancher.io/local-path
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer