apiVersion: v1
kind: ConfigMap
metadata:
  name: media-local-path-config
  namespace: kube-system
data:
  config.json: |
    {
      "nodePathMap":[
        {
          "node":"DEFAULT_PATH_FOR_NON_LISTED_NODES",
          "paths":["/mnt/media/k8s"]
        }
      ]
    }
  setup: |
    #!/bin/sh
    set -eu
    mkdir -m 0777 -p "${VOL_DIR}"
    chmod 700 "${VOL_DIR}/.."
  teardown: |
    #!/bin/sh
    set -eu
    rm -rf "${VOL_DIR}"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: media-local-path-provisioner
  namespace: kube-system
  labels:
    app: media-local-path-provisioner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: media-local-path-provisioner
  template:
    metadata:
      labels:
        app: media-local-path-provisioner
    spec:
      serviceAccountName: local-path-provisioner-service-account
      containers:
        - name: provisioner
          image: rancher/local-path-provisioner:v0.0.31
          command:
            - local-path-provisioner
            - start
            - --config
            - /etc/config/config.json
          volumeMounts:
            - name: config-volume
              mountPath: /etc/config/
      volumes:
        - name: config-volume
          configMap:
            name: media-local-path-config