apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: media-local-path
---
apiVersion: v1
kind: Pod
metadata:
  name: pvc-test
  namespace: media
spec:
  containers:
    - name: busybox
      image: busybox
      command: ["sleep", "3600"]
      volumeMounts:
        - mountPath: "/test"
          name: test-volume
  volumes:
    - name: test-volume
      persistentVolumeClaim:
        claimName: test-pvc