apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc-local
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: local-path