apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    email: jeffrey@indeweygerlings.com
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-staging-private-key
    solvers:
      - dns01:
          cloudflare:
            email: sdkbzq8bqr@privaterelay.appleid.com
            apiTokenSecretRef:
              name: cloudflare-dns-token
              key: api-token