apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  interval: 5m
  path: ./infra/cert-manager
  prune: true
  dependsOn:
    - name: cert-manager-namespace
  sourceRef:
    kind: GitRepository
    name: flux-system