apiVersion: ENC[AES256_GCM,data:sek=,iv:AD5Uzgb7+/usVWdaUcoo+3FLIeZhwfKpzx6QZ6kaD+4=,tag:SvLIz2EgN9FOk5LuQTttxQ==,type:str]
kind: ENC[AES256_GCM,data:NC80+P8z,iv:lR/ABX3Mw04u0UnSrPR0t/uJtxT94cg3FrF0gAPCKoU=,tag:teL4ZN08Xzrya6bPlaFO4g==,type:str]
metadata:
    name: ENC[AES256_GCM,data:PSwlZiP6Vsl3JRwafNmlZYqvOdc=,iv:1u3fW5RHeJQU8FWXM3zCrlFoGBRK2PmY4uM9tmAj4c0=,tag:nrLR71Yfde7v5Y4xuMLgDA==,type:str]
    namespace: ENC[AES256_GCM,data:La0dnUvMnj+qWSPR,iv:lFwzLcQsiq9i3YycHGt09E+GbgFDSAcnhvCMJXcwiXc=,tag:UAarlHepNl6GKL+Fke6C7Q==,type:str]
type: ENC[AES256_GCM,data:ii6IgCtI,iv:dHXu+ymAt2UpbJlJd60NzQ2hvjkJfDFbKgVjB/11SmQ=,tag:CFbwBxdoqgBh9PXW5JME8g==,type:str]
stringData:
    api-token: ENC[AES256_GCM,data:KrN8EIIa3S5JdH8Y2gIvhSb7Va41e5nsRxFy92CksXIfTuUrXQYV0Q==,iv:b7FUpZcBJ02uWLFZBzPvZ4dEC8Uqs68sc5vdM1qSV5g=,tag:q0ShondeNoW6N3uaPoRL4A==,type:str]
sops:
    age:
        - recipient: age1j3xckn88kf6q3lkq37tkgsr2l50j0e8e0d7ckn962v5sw2ddsvqqrry9v5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQcWlub2tVaERDY01PS2Nw
            Q3F1VStQV2tPUkFjMkxwdk1oZ2VEczZrc21RCkxsZEZrbHhWTHNqaHNhMFU4c2o3
            aXo1Y2Rwa2NuOWRiZDV4MDgvbXZZUWsKLS0tIHZtTXgvTlk4ZFJtZlNMRll3OHNK
            dGpycmRwR01vdTFNeGxrTEZPZWdJMDAK3EdhZhRyEEVLwsxuaEdpDTHsNlkluDHx
            xwivshOHwo177rU4OdP66rozFJHesyhcpEH1Uubj7S1cq79jbT68lw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-22T09:11:27Z"
    mac: ENC[AES256_GCM,data:BwSlfJM2IunqPkAi178Wqvboj/6owMdmSQm4XdMfcShkYs72NfJHwFEBiZ8uj+V+/o8uP5o4AvBevYbFLwKcK8ZDU12z/bANBeEEnRC1Ss3NSgrx5w++YJpxlP6I4Jb+s2IkIawbx5BnT8NJ/zCoCCAGECR7e46C3cMqKbf1uLc=,iv:pfQiR98t+Jf9KIGxtKXt/ZzokGdrxZUsdH/OLts9sDo=,tag:G5rmzaLmOXjSbZumWPDIsA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
