apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: odoo
  namespace: odoo
spec:
  interval: 5m
  chart:
    spec:
      chart: odoo
      version: 28.2.4
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    odooUsername: admin
    odooPassword: ""
    odooEmail: admin@example.com
    postgresql:
      enabled: false
    externalDatabase:
      host: odoo-postgresql.odoo.svc.cluster.local
      user: postgres
      password: ""
      database: postgres
    service:
      type: ClusterIP
  valuesFrom:
    - secretRef:
        name: odoo-secrets