apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: odoo
  namespace: odoo
spec:
  interval: 5m
  chart:
    spec:
      chart: odoo
      version: 28.2.4
      sourceRef:
        kind: HelmRepository
        name: bitnami-oci
        namespace: odoo
  values:
    odooUsername: admin
    odooPassword: admin123 # <-- vervang dit door een verwijzing naar een secret
    odooEmail: admin@example.com
    postgresql:
      enabled: false
    externalDatabase:
      host: odoo-postgresql.odoo.svc.cluster.local
      user: postgres
      password: odoo123  # <-- ook deze beveiligen via secret
      database: postgres
    service:
      type: ClusterIP