apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: odoo-postgresql
  namespace: odoo
spec:
  interval: 5m
  chart:
    spec:
      chart: postgresql
      version: "13.2.24"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    auth:
      postgresPassword: odoo123 # <-- vervang met secret
    primary:
      persistence:
        enabled: true
        size: 5Gi