apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
  namespace: kube-system
spec:
  interval: 10m
  chart:
    spec:
      chart: external-dns
      version: "6.28.4"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  install:
    createNamespace: false
  values:
    provider: cloudflare
    extraEnvVars:
      - name: CF_API_TOKEN
        valueFrom:
          secretKeyRef:
            name: cloudflare-dns-token
            key: api-token
    policy: sync
    txtOwnerId: "quantika"
    domainFilters:
      - indeweygerlings.com
      - 4nn1k4.com
    sources:
      - ingress
    logLevel: debug