apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../secrets/cloudflare/cloudflare-dns-token-sealed.yaml
  - ../secrets/standard/standard-secret.yaml
  - externaldns
  - sealed-secrets
  - cert-manager
  - traefik
  - pi-hole
  - storage # Uncomment this line to enable storage