apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cert-manager
  namespace: flux-system  # <- dit is heel belangrijk
spec:
  url: https://charts.jetstack.io
  interval: 10m