apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: pi-hole
  namespace: flux-system
spec:
  url: https://pi-hole.github.io/helm-charts  # The official Pi-hole Helm chart repository
  interval: 10m