apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmChart
metadata:
  name: pi-hole
  namespace: flux-system
spec:
  chart: pi-hole
  version: "5.12.1"
  sourceRef:
    kind: HelmRepository
    name: pi-hole
  interval: 10m # Specify the interval (10 minutes in this case)