apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pihole
  namespace: kube-system
spec:
  interval: 10m
  chart:
    spec:
      chart: pihole
      sourceRef:
        kind: HelmRepository
        name: pi-hole
        namespace: flux-system
  install:
    createNamespace: true
  values:
    webPassword:
      valueFrom:
        secretKeyRef:
          name: standard-secret
          key: password  # Fetches the password from the Secret
    dns:
      localDNS:
        enabled: true
        address: "192.168.50.200"  # The IP of your Kubernetes Master Node (or other local IP)
    service:
      type: ClusterIP  # The DNS service should be internally available via ClusterIP
    ingress:
      ingressClassName: traefik
      enabled: true
      annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /
        external-dns.alpha.kubernetes.io/hostname: pihole.indeweygerlings.com  # Ensure this is set to the correct hostname
        external-dns.alpha.kubernetes.io/owner-id: "quantika"  # Ensure owner-id matches with ExternalDNS setup
        external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"  # Optionally enable Cloudflare proxying
      hosts:
        - pihole.indeweygerlings.com  # Ensure this is set to the correct hostname
      paths:
        - /