apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pi-hole
  namespace: kube-system
spec:
  interval: 10m
  chart:
    spec:
      chart: pihole  # Correct chart name for Bitnami's Pi-hole
      version: "12.0.0"  # Ensure you use a valid version
      sourceRef:
        kind: HelmRepository
        name: pi-hole  # Name of your HelmRepository resource
        namespace: flux-system
  install:
    createNamespace: true
  values:
    webPassword:
      valueFrom:
        secretKeyRef:
          name: standard-secret
          key: password  # Fetches the password from the Secret
    dns:
      localDNS: 
        enabled: true
        address: "192.168.50.200"  # The IP of your Kubernetes Master Node (or other local IP)
    service:
      type: ClusterIP  # The DNS service should be internally available via ClusterIP
    ingress:
      enabled: true
      annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /
      host: pihole.indeweygerlings.com  # Pi-hole web portal is available via this FQDN
      paths:
        - /