apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmChart
metadata:
  name: pi-hole
  namespace: flux-system
spec:
  chart: pi-hole  # This should be a string, not an object
  version: "5.12.1"
  sourceRef:
    kind: HelmRepository
    name: pi-hole
    namespace: flux-system