- name: Ensure mount directory exists
  file:
    path: /mnt/media
    state: directory

- name: Mount USB drive
  mount:
    path: /mnt/media
    src: /dev/sda1
    fstype: xfs
    opts: defaults
    dump: 0
    passno: 2
    state: mounted