apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: kube-system
spec:
  interval: 10m
  chart:
    spec:
      chart: traefik
      version: "24.0.0"
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
  install:
    createNamespace: true
  values:
    deployment:
      enabled: true
    podLabels:
      app: traefik
    service:
      type: LoadBalancer
      annotations:
        external-dns.alpha.kubernetes.io/hostname: "traefik.indeweygerlings.com"
        external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
    ingressRoute:
      dashboard:
        enabled: true
    ports:
      web:
        redirectTo: websecure
      websecure:
        tls:
          enabled: true
    providers:
      kubernetesCRD:
        enabled: true
      kubernetesIngress:
        enabled: true
    certificatesResolvers:
      cloudflare:
        acme:
          email: "jeffrey@indeweygerlings.com"
          storage: "/data/acme.json"
          dnsChallenge:
            provider: cloudflare
            delayBeforeCheck: 0
            resolvers:
              - "1.1.1.1:53"
              - "1.0.0.1:53"
    env:
      - name: CF_API_TOKEN
        valueFrom:
          secretKeyRef:
            name: cloudflare-dns-token
            key: api-token
    additionalArguments:
      - "--certificatesresolvers.cloudflare.acme.dnschallenge=true"
      - "--certificatesresolvers.cloudflare.acme.dnschallenge.provider=cloudflare"
      - "--certificatesresolvers.cloudflare.acme.email=jeffrey@indeweygerlings.com"
      - "--certificatesresolvers.cloudflare.acme.storage=/data/acme.json"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"