apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: kube-system
spec:
  interval: 10m
  chart:
    spec:
      chart: traefik
      version: "24.0.0"
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
  install:
    createNamespace: true
  values:
    api:
      dashboard: true
    deployment:
      enabled: true
      additionalVolumeMounts:
        - name: traefik-data
          mountPath: /data
    additionalVolumes:
      - name: traefik-data
        persistentVolumeClaim:
          claimName: traefik-acme-pvc
    podLabels:
      app: traefik
    service:
      type: NodePort
    ports:
      web:
        port: 80
        nodePort: 30080
        expose: true
        exposedPort: 80
        protocol: TCP
      websecure:
        port: 443
        nodePort: 30443
        expose: true
        exposedPort: 443
        protocol: TCP
        tls:
          enabled: true
      traefik:
        port: 9000
        expose: true
        exposedPort: 9000
        protocol: TCP
    providers:
      kubernetesCRD:
        enabled: true
      kubernetesIngress:
        enabled: true
    certificatesResolvers:
      cloudflare:
        acme:
          email: "jeffrey@indeweygerlings.com"
          storage: "/data/acme.json"
          dnsChallenge:
            provider: cloudflare
            delayBeforeCheck: 0
            resolvers:
              - "1.1.1.1:53"
              - "1.0.0.1:53"
    env:
      - name: CLOUDFLARE_DNS_API_TOKEN
        valueFrom:
          secretKeyRef:
            name: cloudflare-dns-token
            key: api-token
    additionalArguments:
      - "--certificatesresolvers.cloudflare.acme.dnschallenge=true"
      - "--certificatesresolvers.cloudflare.acme.dnschallenge.provider=cloudflare"
      - "--certificatesresolvers.cloudflare.acme.email=jeffrey@indeweygerlings.com"
      - "--certificatesresolvers.cloudflare.acme.storage=/data/acme.json"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.traefik.address=:9000"