apiVersion: v1
kind: Namespace
metadata:
  name: media
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: plex
  namespace: media
spec:
  interval: 10m
  chart:
    spec:
      chart: plex
      version: "6.1.0"
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    createNamespace: true
  values:
    image:
      repository: ghcr.io/linuxserver/plex
      tag: latest
    env:
      PUID: 1000  # pas aan aan je user
      PGID: 1000  # pas aan aan je groep
      VERSION: docker
    service:
      type: NodePort
      port:
        port: 32400
        targetPort: 32400
        nodePort: 32400
    persistence:
      config:
        enabled: true
        existingClaim: plex-config-pvc
      media:
        enabled: true
        type: hostPath
        hostPath: /mnt/media/media
        mountPath: /media