---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-dns-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgCLrAhYeeYvIhiSau0m5I2eRhcV5kb1JgSQM72slkG+/ztoZgj6HMToX58XRnVj5+SU+blzpySRElnuX5v22cS7yPjfJ6K40ANyC2BjIW7qwtf4kS/tXasO+B/Y4pus5lVSdgbmtHtyDS0yaIExhgI9XecWMSr0vKkbFR2TP1XJO4eIAKSBOaKoeLs+JWwgV/REohS1U3t5Qp3uaUOCkOjSqb7+I81FRNK3epxnqxPTM7yejF47/ubPymQSWiNbYN+ydc9fJO0VfQFS6fYE2Cui8O7Tn5olaRsu+JQI98U4EFjr3FqQqTWtekkxsQjITi79IB1wb+YPEv+iJuoFRGklIwEp0rAs2zJ1x+B/+s/6uVdBnSfL98Br18GdZx2uVY+SLbrT3uTs/Ze38qrX7L7BPIjr5w2D7qyB+0wjC6wZSOpwu/wAdrgJ2pyVYLI70/XQN6K0hkJ3Db4PMeJIrjnE+UXgumfFOdzMv1xaAjXVLHI+m3dazMvSB6ZPwlxuDm4562aCmj4lAImZoXnz6BdaFjyD4/eCaPi7gfzZRV0fN0GQHqlni8lgr3CkgUPZlz0rreH3FgH+R8RVWMCPcZ1h6tkNEMfYPPcfRgIg6nrGDgf8qCdbAa7WL9/wQVJz3rvC7TlQFIpSQRdwCkxRFliBrGLIBwvPWsBw+6k8FdUkxHDOHEgM+w8Np/wqAbR6PBCSLnL+04VRIS81/B2TtaJkZNyen3q+5d1ABz5zietCj3TcRDRfEqYG
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-dns-token
      namespace: cert-manager
